-- V8__add_phase3_features.sql
-- Phase 3 Database Schema: Strategy, Signal, Risk Rule, Bar Aggregation

-- =============================================================================
-- 1. Strategies Table (Phase 3.1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS strategies (
    strategy_id CHAR(26) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    strategy_type VARCHAR(32) NOT NULL COMMENT 'MA_CROSSOVER, RSI, etc.',
    status VARCHAR(16) NOT NULL COMMENT 'ACTIVE, INACTIVE, ARCHIVED',
    active_version_id CHAR(26),
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    INDEX idx_strategies_name (name),
    INDEX idx_strategies_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Trading strategies (Phase 3.1)';

-- =============================================================================
-- 2. Strategy Versions Table (Phase 3.1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS strategy_versions (
    strategy_version_id CHAR(26) PRIMARY KEY,
    strategy_id CHAR(26) NOT NULL,
    version_number INT NOT NULL,
    params_json JSON NOT NULL COMMENT 'Strategy parameters as JSON',
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(3) NOT NULL,
    INDEX idx_strategy_versions_strategy (strategy_id),
    INDEX idx_strategy_versions_active (strategy_id, is_active),
    FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Strategy version history (Phase 3.1)';

-- =============================================================================
-- 3. Signals Table (Phase 3.1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS signals (
    signal_id CHAR(26) PRIMARY KEY,
    strategy_id CHAR(26) NOT NULL,
    strategy_version_id CHAR(26) NOT NULL,
    account_id CHAR(26) NOT NULL,
    symbol VARCHAR(16) NOT NULL,
    signal_type VARCHAR(8) NOT NULL COMMENT 'BUY, SELL, HOLD',
    target_type VARCHAR(16) NOT NULL COMMENT 'QTY, VALUE, PERCENT',
    target_value DECIMAL(18,6) NOT NULL,
    ttl_seconds INT,
    reason VARCHAR(255),
    generated_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3),
    INDEX idx_signals_strategy (strategy_id),
    INDEX idx_signals_account_symbol (account_id, symbol),
    INDEX idx_signals_generated_at (generated_at),
    FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Trading signals generated by strategies (Phase 3.1)';

-- =============================================================================
-- 4. Bars Table (Phase 3.1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS bars (
    bar_id CHAR(26) PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    timeframe VARCHAR(8) NOT NULL COMMENT '1m, 5m, 15m, 1h, 1d',
    open_price DECIMAL(18,2) NOT NULL,
    high_price DECIMAL(18,2) NOT NULL,
    low_price DECIMAL(18,2) NOT NULL,
    close_price DECIMAL(18,2) NOT NULL,
    volume BIGINT NOT NULL DEFAULT 0,
    open_time DATETIME(3) NOT NULL,
    close_time DATETIME(3) NOT NULL,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY unique_bar (symbol, timeframe, open_time),
    INDEX idx_bars_symbol_timeframe_time (symbol, timeframe, open_time DESC),
    INDEX idx_bars_symbol_timeframe_closed (symbol, timeframe, is_closed, close_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='OHLCV bar data for strategy evaluation (Phase 3.1)';

-- =============================================================================
-- 5. Risk Rules Table (Phase 3.2)
-- =============================================================================
CREATE TABLE IF NOT EXISTS risk_rules (
    risk_rule_id CHAR(26) PRIMARY KEY,
    scope VARCHAR(16) NOT NULL COMMENT 'GLOBAL, PER_ACCOUNT, PER_SYMBOL',
    account_id CHAR(26),
    symbol VARCHAR(16),
    max_position_value_per_symbol DECIMAL(18,2),
    max_open_orders INT,
    max_orders_per_minute INT,
    daily_loss_limit DECIMAL(18,2),
    consecutive_order_failures_limit INT,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY unique_risk_rule_scope (scope, account_id, symbol),
    INDEX idx_risk_rules_scope_account_symbol (scope, account_id, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Risk management rules with scope hierarchy (Phase 3.2)';

-- =============================================================================
-- 6. Update Risk State Table (Phase 3.2)
-- =============================================================================
-- Add order frequency tracking fields
ALTER TABLE risk_state
ADD COLUMN IF NOT EXISTS order_timestamps JSON
    COMMENT 'Order timestamps for frequency tracking (Phase 3.2)';

ALTER TABLE risk_state
ADD COLUMN IF NOT EXISTS open_order_count INT NOT NULL DEFAULT 0
    COMMENT 'Count of unfilled orders (Phase 3.2)';

-- =============================================================================
-- 7. Update Orders Table (Phase 3.3)
-- =============================================================================
-- Add original values for modification audit trail
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS original_qty DECIMAL(18,6)
    COMMENT 'Original quantity before modification (Phase 3.3)';

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS original_price DECIMAL(18,2)
    COMMENT 'Original price before modification (Phase 3.3)';

-- =============================================================================
-- Insert Default Data
-- =============================================================================

-- Default global risk rule (if not exists)
INSERT IGNORE INTO risk_rules (
    risk_rule_id,
    scope,
    account_id,
    symbol,
    max_position_value_per_symbol,
    max_open_orders,
    max_orders_per_minute,
    daily_loss_limit,
    consecutive_order_failures_limit,
    created_at,
    updated_at
) VALUES (
    '01JFGXYZ0000000000000GLOBAL',
    'GLOBAL',
    NULL,
    NULL,
    5000000.00,  -- 5M KRW per symbol
    10,          -- Max 10 open orders
    5,           -- Max 5 orders per minute
    100000.00,   -- 100K KRW daily loss limit
    5,           -- 5 consecutive failures trigger kill switch
    NOW(3),
    NOW(3)
);

-- =============================================================================
-- End of Migration
-- =============================================================================
